version: '3'
services:
  pinger:
    image: pinger
    ports:
      - "8089:5000"
    environment:
      FLASK_ENV: development
    #volumes:
    #  - .:/app
    networks:
      - services
      - frontend
      - backend
networks:
  services:
    external: true
  frontend:
    external: true
  backend:
    external: true
